"""
YOLO Training Dataset Exporter
Generates YOLO format training bundles containing:
1. images/ - All spectrogram image chunks (<drone_name>_<fs>_<fc>_<dtype>[_0000].jpg)
2. labels/ - YOLO text annotation files (<drone_name>_<fs>_<fc>_<dtype>[_0000].txt)
             Format per line: <class_id> <x_center> <y_center> <width> <height> (normalized to [0.0, 1.0])
3. data.yaml - Standard YOLO training configuration with class mapping
4. signal_parameters_bdw.csv - Detailed RF BDW signal parameters table
5. metadata.json - Session RF parameters & sampling metadata
6. iq/ (optional) - Raw .iq complex64 binary chunks (<drone_name>_<fs>_<fc>_<dtype>[_0000].iq) with optional AWGN SNR adjustment
"""

import os
import io
import zipfile
import csv
import json
import yaml
from datetime import datetime
from typing import Dict, Any, List, Optional, Tuple, Callable
import numpy as np

from backend.rf_processor import RFProcessor, add_awgn
from backend.logger import logger

class YOLOExporter:
    @staticmethod
    def generate_yolo_yaml(classes: List[Dict[str, Any]], dataset_path: str = "./") -> str:
        """
        Generates standard data.yaml for YOLOv5 / YOLOv8 / YOLOv11 training.
        """
        class_names = {idx: c["name"] for idx, c in enumerate(classes)}
        yaml_dict = {
            "path": dataset_path,
            "train": "images",
            "val": "images",
            "nc": len(classes),
            "names": class_names
        }
        yaml_content = f"# YOLO Dataset Configuration\n# Generated by UAV RF Spectrogram Labelling Tool on {datetime.utcnow().isoformat()}Z\n\n"
        yaml_content += yaml.dump(yaml_dict, sort_keys=False, default_flow_style=False)
        return yaml_content

    @staticmethod
    def generate_yolo_labels_for_chunk(
        chunk_annotations: List[Dict[str, Any]],
        classes: List[Dict[str, Any]],
        img_width: int = 1024,
        img_height: int = 512,
        src_width: Optional[int] = None,
        src_height: Optional[int] = None
    ) -> str:
        """
        Generates normalized YOLO format .txt lines for a single chunk.
        Format per line: <class_id> <x_center> <y_center> <width> <height>
        All normalized to [0.0, 1.0].
        """
        class_id_to_idx = {c["id"]: idx for idx, c in enumerate(classes)}
        lines = []

        for ann in chunk_annotations:
            cat_id = ann.get("category_id")
            if cat_id not in class_id_to_idx:
                yolo_class_idx = 0
            else:
                yolo_class_idx = class_id_to_idx[cat_id]

            box_src_w = float(ann.get("img_width") or src_width or img_width or 1024)
            box_src_h = float(ann.get("img_height") or src_height or img_height or 512)

            x = float(ann.get("x", 0.0))
            y = float(ann.get("y", 0.0))
            w = float(ann.get("width", 0.0))
            h = float(ann.get("height", 0.0))

            if w <= 0 or h <= 0:
                continue

            x_center = (x + w / 2.0) / box_src_w
            y_center = (y + h / 2.0) / box_src_h
            w_norm = w / box_src_w
            h_norm = h / box_src_h

            # Clamp coordinates to [0.0, 1.0]
            x_center = min(max(0.0, x_center), 1.0)
            y_center = min(max(0.0, y_center), 1.0)
            w_norm = min(max(0.0, w_norm), 1.0)
            h_norm = min(max(0.0, h_norm), 1.0)

            lines.append(f"{yolo_class_idx} {x_center:.6f} {y_center:.6f} {w_norm:.6f} {h_norm:.6f}")

        return "\n".join(lines) + ("\n" if lines else "")

    @staticmethod
    def generate_yolo_zip_bundle(
        rf_processor: RFProcessor,
        classes: List[Dict[str, Any]],
        annotations_by_chunk: Dict[int, List[Dict[str, Any]]],
        drone_name: Optional[str] = None,
        img_width: int = 1024,
        img_height: int = 512,
        img_format: str = "jpg",
        include_images: bool = True,
        include_labels: bool = True,
        include_csv: bool = True,
        include_iq: bool = False,
        include_video: bool = False,
        include_metadata: bool = True,
        export_snr_db: Optional[float] = None,
        progress_callback: Optional[Callable[[int, str, str, str], None]] = None
    ) -> bytes:
        """
        Creates a complete YOLO dataset ZIP package containing selectable components:
        - images/*.jpg (or .png)
        - labels/*.txt
        - data.yaml
        - signal_parameters_bdw.csv
        - metadata.json
        - (optional) iq/*.iq (raw IQ chunks with optional AWGN)
        - (optional) video/*.mp4 (waterfall video)
        All named according to: <drone_name>_<frequency_sample>_<frequency_center>_<dtype>[_0000].ext
        """
        import concurrent.futures
        import threading

        summary = rf_processor.get_summary()
        effective_drone = drone_name or summary.get("drone_name") or "DJI-MAVIC-PRO-3"
        clean_ext = img_format.lower().lstrip('.')
        if clean_ext not in ["jpg", "jpeg", "png"]:
            clean_ext = "jpg"

        if progress_callback:
            progress_callback(2, "metadata", "Initializing export package...", "Preparing data.yaml & metadata")

        zip_buffer = io.BytesIO()

        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            # 1. Write data.yaml (if labels are included)
            if include_labels:
                yaml_str = YOLOExporter.generate_yolo_yaml(classes=classes)
                zip_file.writestr("data.yaml", yaml_str)

            # 2. Write Metadata JSON
            if include_metadata:
                session_params = {
                    "dataset_format": "yolo",
                    "drone_name": effective_drone,
                    "data_source": summary["source_filename"],
                    "source_format": summary["source_format"],
                    "fs_hz": summary["fs_hz"],
                    "fs_mhz": summary["fs_mhz"],
                    "center_freq_hz": summary["center_freq_hz"],
                    "center_freq_mhz": summary["center_freq_mhz"],
                    "img_width": img_width,
                    "img_height": img_height,
                    "img_format": clean_ext,
                    "total_samples": summary["total_samples"],
                    "total_duration_ms": summary["total_duration_ms"],
                    "total_duration_us": summary["total_duration_us"],
                    "chunk_duration_ms": summary["chunk_duration_ms"],
                    "num_chunks": summary["num_chunks"],
                    "stft_config": summary["stft_config"],
                    "include_images": include_images,
                    "include_labels": include_labels,
                    "include_csv": include_csv,
                    "include_iq_chunks": include_iq,
                    "include_video": include_video,
                    "classes": [{ "id": idx, "name": c["name"], "original_id": c["id"] } for idx, c in enumerate(classes)]
                }
                if export_snr_db is not None:
                    session_params["export_snr_db"] = float(export_snr_db)
                    session_params["awgn_applied_on_export"] = True

                zip_file.writestr("metadata.json", json.dumps(session_params, indent=2))

            # 3. CSV Writer setup
            csv_buf = io.StringIO()
            csv_writer = csv.writer(csv_buf)
            if include_csv:
                csv_writer.writerow([
                    "Annotation_ID", "Image_File", "Label_File", "IQ_File", "Chunk_ID",
                    "Drone_Name", "YOLO_Class_ID", "Category", "Type_of_Signal", "Protocol",
                    "TOA_us", "TOD_us", "PW_us", "FC_MHz", "BW_MHz",
                    "Freq_Low_MHz", "Freq_High_MHz", "SNR_dB",
                    "YOLO_X_Center", "YOLO_Y_Center", "YOLO_W", "YOLO_H",
                    "BBox_X", "BBox_Y", "BBox_W", "BBox_H"
                ])

            class_id_to_idx = {c["id"]: idx for idx, c in enumerate(classes)}
            cat_map = {c["id"]: c["name"] for c in classes}
            cat_dict = {c["id"]: c for c in classes}
            ann_counter = 1
            total_chunks = len(rf_processor.chunks_meta)

            # 4. Render spectrogram images in parallel (if selected)
            rendered_images = {}
            if include_images and total_chunks > 0:
                done_count = 0
                lock = threading.Lock()

                def _render_task(c):
                    c_id = c["id"]
                    img_bytes, _ = rf_processor.render_spectrogram_image(
                        chunk_id=c_id,
                        width=img_width,
                        height=img_height,
                        image_format=clean_ext,
                        target_snr_db=export_snr_db
                    )
                    return c_id, img_bytes

                max_workers = min(os.cpu_count() or 4, 8)
                with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
                    futures = [executor.submit(_render_task, chunk) for chunk in rf_processor.chunks_meta]
                    for f in concurrent.futures.as_completed(futures):
                        c_id, img_bytes = f.result()
                        rendered_images[c_id] = img_bytes
                        with lock:
                            done_count += 1
                            pct = 5 + int(55.0 * (done_count / max(1, total_chunks)))
                            if progress_callback:
                                snr_txt = f" | SNR: {export_snr_db:.1f} dB" if export_snr_db is not None else ""
                                progress_callback(
                                    pct,
                                    "images",
                                    f"Rendering spectrogram image {done_count} / {total_chunks}",
                                    f"{img_width}x{img_height} {clean_ext.upper()}{snr_txt}"
                                )

            # 5. Write images, labels, and compile CSV
            if progress_callback:
                progress_callback(65, "labels", "Formatting YOLO normalized labels and BDW parameters...", "Processing annotations")

            for chunk in rf_processor.chunks_meta:
                c_id = chunk["id"]
                img_name = rf_processor.get_formatted_filename(chunk_id=c_id, extension=clean_ext, drone_name=effective_drone)
                lbl_name = rf_processor.get_formatted_filename(chunk_id=c_id, extension="txt", drone_name=effective_drone)
                iq_name = rf_processor.get_formatted_filename(chunk_id=c_id, extension="iq", drone_name=effective_drone)

                # A. Write spectrogram image
                if include_images:
                    img_bytes = rendered_images.get(c_id)
                    if img_bytes is None:
                        img_bytes, _ = rf_processor.render_spectrogram_image(
                            chunk_id=c_id,
                            width=img_width,
                            height=img_height,
                            image_format=clean_ext,
                            target_snr_db=export_snr_db
                        )
                    zip_file.writestr(f"images/{img_name}", img_bytes)

                # B. Generate and write YOLO label txt
                raw_boxes = annotations_by_chunk.get(c_id, []) or annotations_by_chunk.get(str(c_id), [])
                if include_labels:
                    lbl_txt = YOLOExporter.generate_yolo_labels_for_chunk(
                        chunk_annotations=raw_boxes,
                        classes=classes,
                        img_width=img_width,
                        img_height=img_height,
                        src_width=rf_processor.render_width,
                        src_height=rf_processor.render_height
                    )
                    zip_file.writestr(f"labels/{lbl_name}", lbl_txt)

                # C. Record annotations in CSV if selected
                if include_csv:
                    for box in raw_boxes:
                        cat_id = box.get("category_id")
                        yolo_idx = class_id_to_idx.get(cat_id, 0)
                        cat_name = cat_map.get(cat_id, "Unknown")
                        cat_info = cat_dict.get(cat_id, {"type_of_signal": "Unknown", "protocol": "Unknown"})

                        box_src_w = float(box.get("img_width") or rf_processor.render_width or 1024)
                        box_src_h = float(box.get("img_height") or rf_processor.render_height or 512)

                        x = float(box.get("x", 0.0))
                        y = float(box.get("y", 0.0))
                        w = float(box.get("width", 0.0))
                        h = float(box.get("height", 0.0))

                        x_center = min(max(0.0, (x + w / 2.0) / box_src_w), 1.0)
                        y_center = min(max(0.0, (y + h / 2.0) / box_src_h), 1.0)
                        w_norm = min(max(0.0, w / box_src_w), 1.0)
                        h_norm = min(max(0.0, h / box_src_h), 1.0)

                        bdw = box.get("bdw") or rf_processor.calculate_bdw_parameters(
                            chunk_id=c_id,
                            bbox=[x, y, w, h],
                            img_width=int(box_src_w),
                            img_height=int(box_src_h),
                            signal_type=cat_info.get("type_of_signal"),
                            protocol=cat_info.get("protocol")
                        )

                        snr_val = float(export_snr_db) if export_snr_db is not None else bdw.get("snr_db", 0.0)

                        csv_writer.writerow([
                            ann_counter,
                            img_name if include_images else "",
                            lbl_name if include_labels else "",
                            iq_name if include_iq else "",
                            c_id,
                            effective_drone,
                            yolo_idx,
                            cat_name,
                            bdw.get("type_of_signal", ""),
                            bdw.get("protocol", ""),
                            bdw.get("toa_us", ""),
                            bdw.get("tod_us", ""),
                            bdw.get("pw_us", ""),
                            bdw.get("fc_mhz", ""),
                            bdw.get("bw_mhz", ""),
                            bdw.get("freq_low_mhz", ""),
                            bdw.get("freq_high_mhz", ""),
                            round(snr_val, 1),
                            round(x_center, 6),
                            round(y_center, 6),
                            round(w_norm, 6),
                            round(h_norm, 6),
                            round(x, 2),
                            round(y, 2),
                            round(w, 2),
                            round(h, 2)
                        ])
                        ann_counter += 1

            if include_csv:
                zip_file.writestr("signal_parameters_bdw.csv", csv_buf.getvalue())

            # 6. Optionally write raw .iq chunks (Optimized: single-pass AWGN & ZIP_STORED zero-compression)
            if include_iq and rf_processor.iq_data is not None:
                global_noisy_iq = None
                if export_snr_db is not None:
                    global_noisy_iq = add_awgn(rf_processor.iq_data, snr_db=float(export_snr_db))

                for i, chunk in enumerate(rf_processor.chunks_meta):
                    c_id = chunk["id"]
                    meta = rf_processor.chunks_meta[c_id]
                    if global_noisy_iq is not None:
                        iq_slice = global_noisy_iq[meta["start_idx"]:meta["end_idx"]]
                    else:
                        iq_slice = rf_processor.iq_data[meta["start_idx"]:meta["end_idx"]]

                    iq_name = rf_processor.get_formatted_filename(chunk_id=c_id, extension="iq", drone_name=effective_drone)
                    zip_file.writestr(f"iq/{iq_name}", iq_slice.tobytes(), compress_type=zipfile.ZIP_STORED)
                    if progress_callback:
                        pct = 75 + int(10.0 * ((i + 1) / max(1, total_chunks)))
                        progress_callback(
                            pct,
                            "iq",
                            f"Slicing raw IQ chunk {i+1} / {total_chunks}",
                            f"Raw Complex64 ({len(iq_slice):,} samples)"
                        )

            # 7. Optionally render and write continuous waterfall video
            if include_video and len(rf_processor.chunks_meta) > 0:
                if progress_callback:
                    progress_callback(85, "video", "Rendering continuous waterfall MP4 video...", "Encoding H.264 frames")
                try:
                    import tempfile
                    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp_vid:
                        tmp_vid_path = tmp_vid.name
                    rf_processor.render_waterfall_video(
                        output_filepath=tmp_vid_path,
                        fps=10.0,
                        width=img_width,
                        height=img_height
                    )
                    vid_name = f"waterfall_{effective_drone}.mp4"
                    with open(tmp_vid_path, "rb") as vf:
                        zip_file.writestr(f"video/{vid_name}", vf.read())
                    if os.path.exists(tmp_vid_path):
                        os.remove(tmp_vid_path)
                except Exception as e:
                    logger.error(f"Error embedding waterfall video in YOLO ZIP: {e}")

            if progress_callback:
                progress_callback(95, "packaging", "Compressing dataset ZIP archive...", "Finalizing package")

        zip_bytes = zip_buffer.getvalue()
        zip_size_mb = len(zip_bytes) / (1024 * 1024)
        logger.info(f"Generated YOLO training dataset ZIP bundle ({zip_size_mb:.2f} MB, include_iq={include_iq}, include_video={include_video}, export_snr_db={export_snr_db}, drone={effective_drone}, res={img_width}x{img_height}).")
        return zip_bytes
